name: Build SLib Idea Plugin (snapshots)

on: push
concurrency: slib_idea_plugin
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew buildPlugin
      - name: Upload the final artifact
        uses: actions/upload-artifact@v2
        with:
          path: build/distributions/*.zip
